apiVersion: transaction.mesh-shaped.top/v1alpha1
kind: Seller
metadata:
  labels:
    app.kubernetes.io/name: seller
    app.kubernetes.io/instance: seller-sample
    app.kubernetes.io/part-of: k8s-crd-tutorial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-crd-tutorial
  name: seller-sample
spec:
  # TODO(user): Add fields here
