apiVersion: transaction.mesh-shaped.top/v1alpha1
kind: Buyer
metadata:
  labels:
    app.kubernetes.io/name: buyer
    app.kubernetes.io/instance: buyer-sample
    app.kubernetes.io/part-of: k8s-crd-tutorial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-crd-tutorial
  name: buyer-sample
spec:
  name: "sample"
  price: "100.00"
  amount: 10
