/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
plugins {
    idea
    kotlin("jvm") version "1.3.10"
}

idea {
    module {
        outputDir = file("$buildDir/classes/main")
        testOutputDir = file("$buildDir/classes/test")
    }
}

val junit5ApiVersion = "5.3.0"
val junit5PlatformVersion = "1.3.0"
val assertjVersion = "3.11.1"

dependencies {
    compile(kotlin("stdlib-jdk8"))
    compile(kotlin("reflect"))
    testCompile(kotlin("test"))
    testCompile(kotlin("test-junit"))

    testCompile("org.junit.jupiter:junit-jupiter-api:$junit5ApiVersion")
    testCompile("org.junit.jupiter:junit-jupiter-engine:$junit5ApiVersion")
    testCompile("org.junit.jupiter:junit-jupiter-params:$junit5ApiVersion")
    testCompile("org.junit.platform:junit-platform-runner:$junit5PlatformVersion")
    testCompile("org.junit.platform:junit-platform-launcher:$junit5PlatformVersion")

    testCompile("org.assertj:assertj-core:$assertjVersion")
}