# permissions for end users to edit buyers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: buyer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-crd-tutorial
    app.kubernetes.io/part-of: k8s-crd-tutorial
    app.kubernetes.io/managed-by: kustomize
  name: buyer-editor-role
rules:
- apiGroups:
  - transaction.mesh-shaped.top
  resources:
  - buyers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transaction.mesh-shaped.top
  resources:
  - buyers/status
  verbs:
  - get
