# permissions for end users to view sellers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: seller-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-crd-tutorial
    app.kubernetes.io/part-of: k8s-crd-tutorial
    app.kubernetes.io/managed-by: kustomize
  name: seller-viewer-role
rules:
- apiGroups:
  - transaction.mesh-shaped.top
  resources:
  - sellers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transaction.mesh-shaped.top
  resources:
  - sellers/status
  verbs:
  - get
